### ISSUE TITLE
yarn build error

### ISSUE THREAD

**Issue by sourcier** [everydayhero/boilermaker#39]
The following error is produced when you you run ```yarn build```:

```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at writeOut (/Users/rrajaratnam/Tresors/blackbaud/christmas-jumper-day/node_modules/webpack/lib/Compiler.js:447:26)
    at asyncLib.forEachLimit (/Users/rrajaratnam/Tresors/blackbaud/christmas-jumper-day/node_modules/webpack/lib/Compiler.js:466:7)
    at objectIteratorWithKey (/Users/rrajaratnam/Tresors/blackbaud/christmas-jumper-day/node_modules/neo-async/async.js:3509:9)
    at timesSync (/Users/rrajaratnam/Tresors/blackbaud/christmas-jumper-day/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/rrajaratnam/Tresors/blackbaud/christmas-jumper-day/node_modules/neo-async/async.js:3463:5)
    at emitFiles (/Users/rrajaratnam/Tresors/blackbaud/christmas-jumper-day/node_modules/webpack/lib/Compiler.js:358:13)
    at /Users/rrajaratnam/Tresors/blackbaud/christmas-jumper-day/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sourcier** [comment]
My project was bootstrapped with:
Boilermaker v2.1.1

Downgrading the following packages from:
```
"boiler-room-builder": "^3.0.1",
"boiler-room-runner": "^2.0.0",
```

to:

```
"boiler-room-builder": "^2.0.4",
"boiler-room-runner": "^1.4.3",
```

Resolves the issue.
